name: Docker Image CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run test ubuntu
      run: docker build . --file test/DockerfileTest_ubuntu --build-arg VARIANT="ubuntu:24.04" --build-arg GDB_VERSION="16.3" --tag core_analyzer:ubuntu$(date +%s)
    - name: Run test redhat
      run: docker build . --file test/DockerfileTest_redhat --build-arg VARIANT="redhat/ubi10" --build-arg GDB_VERSION="16.3" --tag core_analyzer:rdht$(date +%s)
    - name: Run test fedora
      run: docker build . --file test/DockerfileTest_redhat --build-arg VARIANT="fedora:41" --build-arg GDB_VERSION="16.3" --tag core_analyzer:rdht$(date +%s)
    - name: Run test suse
      run: docker build . --file test/DockerfileTest_suse --build-arg VARIANT="opensuse/leap:15.6" --build-arg GDB_VERSION="12.1" --tag core_analyzer:suse$(date +%s)
    - name: Run test 9
      run: docker build . --file test/DockerfileTest_gdb_9_2 --tag core_analyzer:9_2$(date +%s)
